apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: python-app-applicationset
  namespace: argocd
  resourceVersion: "592048"
  uid: c1856717-67e7-42a7-b4cb-dec61f656ccc
  creationTimestamp: 2026-01-01T12:24:38.000Z
spec:
  generators:
    - list:
        elements:
          - cluster: kind-kind
            namespace: default
            environment: kind-kind
          - cluster: minikube
            namespace: default
            environment: minikube
  template:
    metadata:
      name: python-app-{{environment}}
    spec:
      project: default
      source:
        repoURL: https://github.com/tejassassin/python-app.git
        targetRevision: main
        path: .
        helm:
          releaseName: python-app-{{environment}}
          valueFiles:
            - values-{{environment}}.yaml
      destination:
        name: "{{cluster}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
