apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: python-app-applicationset
  namespace: argocd
  resourceVersion: "589412"
  uid: 432858c6-7ac8-4811-aac6-0126405d119a
  creationTimestamp: 2026-01-01T11:56:16.000Z
spec:
  generators:
    - list:
        elements:
          - cluster: kind-kind
            namespace: default
            server: https://127.0.0.1:51476
            environment: kind-kind
          - cluster: minikube
            namespace: default
            server: https://127.0.0.1:54901
            environment: minikube
  template:
    metadata:
      name: python-app-{{environment}}
    spec:
      project: default
      source:
        repoURL: https://github.com/tejassassin/python-app.git
        targetRevision: main
        path: .
        helm:
          releaseName: python-app-{{environment}}
      destination:
        server: "{{cluster}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
