apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: python-app-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: kind-kind
            namespace: default
            environment: kind-kind
  template:
    metadata:
      name: python-app-{{environment}}
    spec:
      project: default
      source:
        repoURL: https://github.com/tejassassin/python-app.git
        targetRevision: main
        path: .
        helm:
          releaseName: python-app-{{environment}}
          valueFiles:
            - values-{{environment}}.yaml
      destination:
        name: "{{cluster}}"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
